openapi: 3.0.3
info:
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: BoR Valuable Badge Database
  version: 1.0.0
servers:
- url: https://example.com/api/v3
tags:
- description: Database lookup
  name: query
- description: Database management available to all users
  name: user
- description: Database management available to admins
  name: admin
paths:
  /admin/dumpdb:
    get:
      operationId: admin_dump_dbget
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Database'
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Get a dump of the entire database right now
      tags:
      - admin
      x-openapi-router-controller: borValBadgeDbServer.controllers.admin_controller
  /admin/purgebadgeinfos:
    get:
      operationId: admin_purge_badge_infos_get
      parameters:
      - description: The CSV of badge ids
        explode: true
        in: query
        name: badgeIds
        required: true
        schema:
          items:
            type: integer
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_admin_purgebadgeinfos_get_200_response'
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Purge cached info of badges
      tags:
      - admin
      x-openapi-router-controller: borValBadgeDbServer.controllers.admin_controller
    post:
      operationId: admin_purge_badge_infos_post
      requestBody:
        content:
          text/plain:
            schema:
              example: "2124469124"
              type: string
        description: The CSV of badge ids
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_admin_purgebadgeinfos_get_200_response'
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Purge cached info of badges
      tags:
      - admin
      x-openapi-router-controller: borValBadgeDbServer.controllers.admin_controller
  /admin/purgeuniverseinfos:
    get:
      operationId: admin_purge_universe_infos_get
      parameters:
      - description: The CSV of universe ids
        explode: true
        in: query
        name: universeIds
        required: true
        schema:
          items:
            type: integer
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_admin_purgebadgeinfos_get_200_response'
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Purge cached info of universes and all associated badges
      tags:
      - admin
      x-openapi-router-controller: borValBadgeDbServer.controllers.admin_controller
    post:
      operationId: admin_purge_universe_infos_post
      requestBody:
        content:
          text/plain:
            schema:
              example: "1159511221"
              type: string
        description: The CSV of universe ids
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_admin_purgebadgeinfos_get_200_response'
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Purge cached info of universes and all associated badges
      tags:
      - admin
      x-openapi-router-controller: borValBadgeDbServer.controllers.admin_controller
  /admin/refreshdb:
    get:
      operationId: admin_refresh_db_get
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_admin_purgebadgeinfos_get_200_response'
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Redetermine values of all badges in the database and compact it
      tags:
      - admin
      x-openapi-router-controller: borValBadgeDbServer.controllers.admin_controller
  /admin/savedb:
    get:
      operationId: admin_save_dbget
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Save the database right now
      tags:
      - admin
      x-openapi-router-controller: borValBadgeDbServer.controllers.admin_controller
  /admin/startcheck:
    get:
      operationId: admin_start_check_get
      parameters:
      - description: The universe id to check
        explode: true
        in: query
        name: universeId
        required: true
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_user_requestcheck_get_200_response'
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Start a check/recheck of an universe
      tags:
      - admin
      x-openapi-router-controller: borValBadgeDbServer.controllers.admin_controller
  /query/bybadgeids:
    get:
      operationId: query_by_badge_ids_get
      parameters:
      - description: The CSV of badge ids
        explode: true
        in: query
        name: badgeIds
        required: true
        schema:
          items:
            type: integer
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_query_bybadgeids_get_200_response'
          description: OK
      summary: Look up creation dates and values of badge ids
      tags:
      - query
      x-openapi-router-controller: borValBadgeDbServer.controllers.query_controller
    post:
      operationId: query_by_badge_ids_post
      requestBody:
        content:
          text/plain:
            schema:
              example: "2124469124"
              type: string
        description: The CSV of badge ids
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_query_bybadgeids_get_200_response'
          description: OK
      summary: Look up creation dates and values of badge ids
      tags:
      - query
      x-openapi-router-controller: borValBadgeDbServer.controllers.query_controller
  /query/byuniverseids:
    get:
      operationId: query_by_universe_ids_get
      parameters:
      - description: The CSV of universe ids
        explode: true
        in: query
        name: universeIds
        required: true
        schema:
          items:
            type: integer
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_query_byuniverseids_get_200_response'
          description: OK
      summary: Look up creation dates and values of all badges under universes
      tags:
      - query
      x-openapi-router-controller: borValBadgeDbServer.controllers.query_controller
    post:
      operationId: query_by_universe_ids_post
      requestBody:
        content:
          text/plain:
            schema:
              example: "1159511221"
              type: string
        description: The CSV of universe ids
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_query_byuniverseids_get_200_response'
          description: OK
      summary: Look up creation dates and values of all badges under universes
      tags:
      - query
      x-openapi-router-controller: borValBadgeDbServer.controllers.query_controller
  /user/reportmissing:
    get:
      operationId: user_report_missing_get
      parameters:
      - description: The CSV of badge ids
        explode: true
        in: query
        name: badgeIds
        required: true
        schema:
          items:
            type: integer
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_user_reportmissing_get_200_response'
          description: OK
      summary: Run checks based on missing/unknown badge ids
      tags:
      - user
      x-openapi-router-controller: borValBadgeDbServer.controllers.user_controller
    post:
      operationId: user_report_missing_post
      requestBody:
        content:
          text/plain:
            schema:
              example: "2124469124"
              type: string
        description: The CSV of badge ids
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_user_reportmissing_get_200_response'
          description: OK
      summary: Run checks based on missing/unknown badge ids
      tags:
      - user
      x-openapi-router-controller: borValBadgeDbServer.controllers.user_controller
  /user/requestcheck:
    get:
      operationId: user_request_check_get
      parameters:
      - description: The universe id to check
        explode: true
        in: query
        name: universeId
        required: true
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_user_requestcheck_get_200_response'
          description: OK
      summary: Request a check/recheck of an universe. Gets ignored if the universe
        was last checked <5 mins ago
      tags:
      - user
      x-openapi-router-controller: borValBadgeDbServer.controllers.user_controller
components:
  schemas:
    BadgeInfo:
      example:
        found: true
        created: 1558655968690
        badge_id: 2124469124
        awarding_universe: 1159511221
        value: 2
      properties:
        badge_id:
          example: 2124469124
          title: badge_id
          type: integer
        found:
          example: true
          title: found
          type: boolean
        created:
          example: 1558655968690
          title: created
          type: integer
        awarding_universe:
          example: 1159511221
          title: awarding_universe
          type: integer
        value:
          example: 2
          title: value
          type: integer
      title: BadgeInfo
      type: object
    UniverseInfo:
      example:
        badges:
          "2124469124":
            badge_id: 2124469124
            found: true
            created: 1558655968690
            awarding_universe: 1159511221
            value: 2
        found: true
        last_checked: 1683424605340
        universe_id: 1159511221
        name: "[30,000 Badges] Manner's Badge Walk"
        free_badges:
        - 2124960830
        - 2124960830
        badge_count: 30000
      properties:
        universe_id:
          example: 1159511221
          title: universe_id
          type: integer
        found:
          example: true
          title: found
          type: boolean
        last_checked:
          example: 1683424605340
          title: last_checked
          type: integer
        name:
          example: "[30,000 Badges] Manner's Badge Walk"
          title: name
          type: string
        badge_count:
          example: 30000
          title: badge_count
          type: integer
        free_badges:
          items:
            example: 2124960830
            type: integer
          title: free_badges
          type: array
        badges:
          additionalProperties:
            $ref: '#/components/schemas/BadgeInfo'
          example:
            "2124469124":
              badge_id: 2124469124
              found: true
              created: 1558655968690
              awarding_universe: 1159511221
              value: 2
          title: badges
          type: object
      title: UniverseInfo
      type: object
    Database:
      example:
        universes:
          "1159511221":
            universe_id: 1159511221
            found: true
            last_checked: 1683424605340
            name: "[30,000 Badges] Manner's Badge Walk"
            badge_count: 30000
            free_badges:
            - 2124960830
            badges:
              "2124469124":
                badge_id: 2124469124
                found: true
                created: 1558655968690
                awarding_universe: 1159511221
                value: 2
      properties:
        universes:
          additionalProperties:
            $ref: '#/components/schemas/UniverseInfo'
          example:
            "1159511221":
              universe_id: 1159511221
              found: true
              last_checked: 1683424605340
              name: "[30,000 Badges] Manner's Badge Walk"
              badge_count: 30000
              free_badges:
              - 2124960830
              badges:
                "2124469124":
                  badge_id: 2124469124
                  found: true
                  created: 1558655968690
                  awarding_universe: 1159511221
                  value: 2
          title: universes
          type: object
      title: Database
      type: object
    _query_bybadgeids_get_200_response:
      example:
        data:
        - found: true
          created: 1558655968690
          badge_id: 2124469124
          awarding_universe: 1159511221
          value: 2
        - found: true
          created: 1558655968690
          badge_id: 2124469124
          awarding_universe: 1159511221
          value: 2
      properties:
        data:
          items:
            $ref: '#/components/schemas/BadgeInfo'
          title: data
          type: array
      title: _query_bybadgeids_get_200_response
      type: object
    _query_byuniverseids_get_200_response:
      example:
        data:
        - badges:
            "2124469124":
              badge_id: 2124469124
              found: true
              created: 1558655968690
              awarding_universe: 1159511221
              value: 2
          found: true
          last_checked: 1683424605340
          universe_id: 1159511221
          name: "[30,000 Badges] Manner's Badge Walk"
          free_badges:
          - 2124960830
          - 2124960830
          badge_count: 30000
        - badges:
            "2124469124":
              badge_id: 2124469124
              found: true
              created: 1558655968690
              awarding_universe: 1159511221
              value: 2
          found: true
          last_checked: 1683424605340
          universe_id: 1159511221
          name: "[30,000 Badges] Manner's Badge Walk"
          free_badges:
          - 2124960830
          - 2124960830
          badge_count: 30000
      properties:
        data:
          items:
            $ref: '#/components/schemas/UniverseInfo'
          title: data
          type: array
      title: _query_byuniverseids_get_200_response
      type: object
    _user_requestcheck_get_200_response:
      example:
        last_checked: 1683424605340
        check_in_progress: true
      properties:
        last_checked:
          example: 1683424605340
          title: last_checked
          type: integer
        check_in_progress:
          example: true
          title: check_in_progress
          type: boolean
      title: _user_requestcheck_get_200_response
      type: object
    _user_reportmissing_get_200_response:
      example:
        added_to_queue: 0
        missing_badges: 0
      properties:
        added_to_queue:
          example: 0
          title: added_to_queue
          type: integer
        missing_badges:
          example: 0
          title: missing_badges
          type: integer
      title: _user_reportmissing_get_200_response
      type: object
    _admin_purgebadgeinfos_get_200_response:
      example:
        badges_affected: 0
      properties:
        badges_affected:
          example: 0
          title: badges_affected
          type: integer
      title: _admin_purgebadgeinfos_get_200_response
      type: object
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: api_key
      type: apiKey
      x-apikeyInfoFunc: borValBadgeDbServer.controllers.security_controller_.info_from_ApiKeyAuth
